#!/usr/bin/python
import oauth2 as oauth
import sys
import urllib

CONSUMER_KEY=''
CONSUMER_SECRET=''
ACCESS_TOKEN=''
ACCESS_SECRET=''

if __name__ == "__main__":
	try:
		message = sys.argv[1]
	except IndexError:
		print "No message specified"
		sys.exit(1)
	else:
		token = oauth.Token(ACCESS_TOKEN, ACCESS_SECRET)
		consumer = oauth.Consumer(CONSUMER_KEY, CONSUMER_SECRET)
		client = oauth.Client(consumer, token)

		data = {'status': message[:137]}
		resp, content = client.request('https://api.twitter.com/1/statuses/update.json', 'POST', urllib.urlencode(data))
		if resp['status'] == '200':
			print "Done"
			sys.exit(0)
		else:
			print "Error"
			print resp
			sys.exit(1)
